### ISSUE TITLE
Libguestfs mounting method is extremely slow

### ISSUE THREAD

**Issue by 64** [managarm/bootstrap-managarm#114]
On xbbs it takes ~40 minutes for the full image.

**Comment by ArsenArsen** [comment]
In my testing, populating the rootfs with `mke2fs` looks like a very viable option. This is blocked on someone looking into https://github.com/managarm/managarm/issues/384

**Comment by avdgrinten** [comment]
Is that issue reproducible if the image is created in that way?

**Comment by ArsenArsen** [comment]
https://github.com/managarm/managarm/issues/384 is consistently reproducible if the image is initialized with it, yes, the command is stated in the issue

**Comment by ArsenArsen** [comment]
solved, I think, the image step now takes under a minute
