### ISSUE TITLE
Problem with compile

### ISSUE THREAD

**Issue by japiotr123** [managarm/bootstrap-managarm#2]
Hello
I have problem with compile with xbstrap
`make[1]: Wejście do katalogu '/home/japiotr123/hdd/managarm/build/tool-builds/system-gcc/isl'
CDPATH="${ZSH_VERSION+.}:" && cd /home/japiotr123/hdd/managarm/build/../src/ports/gcc/isl && /bin/sh /home/japiotr123/hdd/managarm/src/ports/gcc/isl/missing aclocal-1.15 -I m4
/home/japiotr123/hdd/managarm/src/ports/gcc/isl/missing: 81: /home/japiotr123/hdd/managarm/src/ports/gcc/isl/missing: aclocal-1.15: not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[1]: *** [Makefile:1202: /home/japiotr123/hdd/managarm/build/../src/ports/gcc/isl/aclocal.m4] Błąd 127
make[1]: Opuszczenie katalogu '/home/japiotr123/hdd/managarm/build/tool-builds/system-gcc/isl'
make: *** [Makefile:6166: all-isl] Błąd 2
xbstrap: Action compile-tool of tool stage ('system-gcc', 'compiler') failed
`

I would be grateful for help

**Comment by thomtl** [comment]
Have you installed all the deps as outlined in README.md?
As far as i can see the deps you're missing is `autotools` but it's also noting about `m4` and `perl` so it might be worth it to install those too

**Comment by avdgrinten** [comment]
This seems to be a problem with building GCC. It does not find the `aclocal` binary. We're building automake ourselfs and it should be part of that package (?). Can you post the full build log (e.g., as a gist), preferably in English (`export LANG=en_US.UTF8` or similar)?

**Comment by japiotr123** [comment]
Hello
Previously I had version 1.6 when xbstrap want to use 1.5. I complile 1.5 version and added to path and it helps.
