### ISSUE TITLE
Work on getting proper GLX support

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/bootstrap-managarm#42]
With the recent additions of several xorg libraries, effort can be made into building `libGL.so` from mesa and enabling proper OpenGL support in managarm. While locally, mesa builds `libGL.so` fine with few modifications, at runtime concerns have arisen that (a part of) the xorg server is needed. While we (currently) do not intend on porting the complete xorg stack, porting `xwayland` and supporting programs should allow `libGL.so` to be useful.

For this to be possible, the following (incomplete) list of programs need to be ported and/or upgraded:

- [x] `xorg-server`, for now `xwayland` is good enough. There are still some runtime issues for `xorg-server` to run and for clients to be able to work
- [x] `libdrm` upgrade to at least 2.4.89
- [x] `libxfont2`, direct dependency of `xorg-server`
- [x] `libfontenc`, dependency of `libxfont2`
- [x] `font-util`, both as a host-tool and on managarm, build-time and possible run-time dependencies of several packages in this list
- [x] `libxkbfile`, direct dependency of `xorg-server`
- [x] `xkbcomp`, dependency of `xorg-server`
- [x] a nice demo, preferably `glxgears` (will be implemented in #48)

This issue serves as a categorizing and tracking issue, making it easier to label pull requests as being part of porting `xwayland`

**Comment by avdgrinten** [comment]
Note that libGL is *GLX* support, not OpenGL support. OpenGL support (via EGL) is already supposed on Managarm. (But some programs still rely on GLX instead of EGL.)
